openapi: 3.0.0
info:
  title: YumeTravel Backend API
  version: 1.0.0
paths:
  /create_conversation:
    get:
      summary: Create a new conversation
      responses:
        '200':
          description: Conversation has been created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    description: Current Conversation Session
                    type: string
  /query:
    get:
      summary: Get query by message
      parameters:
        - in: query
          name: message
          schema:
            type: string
        - in: query
          name: conversation_id
          schema:
            type: string
      responses:
        '200':
          description: Querying Instance has been initiated successfully on the server
  /conversation:
    post:
      summary: Handle conversation events
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
  /message:
    post:
      summary: Create a new message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                conversation_id:
                  type: string
      responses:
        '200':
          description: Successful response